### ISSUE TITLE
--no-progress is not shown in help, and not working

### ISSUE THREAD

**Issue by marcelloh** [JakubOnderka/PHP-Parallel-Lint#101]
Just pulled this package via composer, and it is not working.

Showing:
Invalid option --no-progress

:-(

**Comment by JakubOnderka** [comment]
Yes, that is because you download latest stable version 0.9.2, but the option --no-progress works only in current master. But version 1.0 will be released soon, stay tunned :)

**Comment by pajon** [comment]
Hello, how it looks like with 1.0 ?

**Comment by JakubOnderka** [comment]
Version 1.0 was released :)
