### ISSUE TITLE
Exclude parameter ignored for files listed on command line

### ISSUE THREAD

**Issue by flow-control** [JakubOnderka/PHP-Parallel-Lint#102]
Hello,

i don't know if this behavior is intended, but i found it to be wrong:
```
./vendor/bin/parallel-lint --exclude core core/test.php
PHP 7.1.7 | 10 parallel jobs
X                                                            1/1 (100 %)


Checked 1 files in 0 seconds
Syntax error found in 1 file

------------------------------------------------------------
Parse error: core/test.php:3
    1| <?php
    2| foo
Unexpected end of file
```

If i just call it with `.` instead of the file name, the `core` directory is not checked as expected.

Kind regards
Florian

**Comment by VincentChataignier** [comment]
Command : `./vendor/bin/prallel-lint --exclude [dirs|files] [paths]`

Yes, I think this is an expected behavior because : 
 - `exclude` option is use only with directory not with file
 - directories or files is excluded only if they are in `paths`

**Comment by flow-control** [comment]
Ok, you are right, this would than be a feature ;-)
