### ISSUE TITLE
Extension filter does not work for combined extension

### ISSUE THREAD

**Issue by ohartl** [JakubOnderka/PHP-Parallel-Lint#115]
When I want to check files with extension `.php.dist` (Distribution configs) I currently need to specify `-e php,dist`, which would for example also try to lint `*.xml.dist` files.

I'd like the `-e` option to be able to handle these combined extensions, so I can pass `-e php,php.dist`, filtering only php files and "distrubution" php files. (This also works in tools like phpcs, ...

I could help implementing it.
PS: The title might not be that nice. Just update it if something else fits better.

**Comment by jrfnl** [comment]
PR #151 addresses this issue.

**Comment by grogy** [comment]
Hello @ohartl this PR was merged. Great work from @jrfnl

**Comment by ohartl** [comment]
Awesome! thanks a lot @jrfnl for your work
