### ISSUE TITLE
Create new stable version

### ISSUE THREAD

**Issue by robertfausk** [JakubOnderka/PHP-Parallel-Lint#130]
Can you please tag a new release? (Because of checkstyle support and so on...)
Thanks in advance :)

**Comment by kamazee** [comment]
Same here.

@JakubOnderka I vaguely recall you mentioned several prerequisite you'd like to match before cutting a new version (it was rather long time ago, though); is there anything outstanding? If there is, do you need a hand with anything? I'll be glad to help to stop pinpointing my composer.lock to a specific commit :)

**Comment by kostajh** [comment]
+1, especially for #125 as phan will fail analysis on projects that use this project.

**Comment by jbouzekri** [comment]
+1

**Comment by robertfausk** [comment]
@JakubOnderka Still waiting for the new release :clap:

**Comment by szepeviktor** [comment]
v1.1.0 is released over here: https://github.com/grogy/PHP-Parallel-Lint/tree/v1.1.0

**Comment by robertfausk** [comment]
Thanks!
