### ISSUE TITLE
composer: use separate autoload and autoload-dev

### ISSUE THREAD

**Issue by mfn** [JakubOnderka/PHP-Parallel-Lint#140]
Currently the whole project tree is marked for `autoload`, from `composer.json`
```json
    "autoload": {
        "classmap": [
            "./"
        ]
    },
```
It does not differentiate between autoloading actual source and test related stuff, but should.

(unverified) suggestion:
```json
    "autoload": {
        "classmap": [
            "./src/"
        ]
    },
    "autoload-dev": {
      "classmap": [
        "./tests/"
      ]
    }  
```

**Comment by jrfnl** [comment]
A PR is open to address in https://github.com/php-parallel-lint/PHP-Parallel-Lint/pull/88

**Comment by grogy** [comment]
PR was merged. Thanks @mfn for suggestion and @jrfnl for pushing as PR :+1:

**Comment by mfn** [comment]
Nice, closing then!
