### ISSUE TITLE
Lint error on FacebookAds

### ISSUE THREAD

**Issue by codeasashu** [JakubOnderka/PHP-Parallel-Lint#142]
I am running parallel-lint

`vendor/bin/parallel-lint --exclude vendor .`

Got this error:
```sh
Parse error: ./app/app/Vendor/FacebookAds/facebook/php-ads-sdk/examples/aggregator_onboarding/api.php:134
    132|       'client_user_id' => $app_scoped_user_id,
    133|     ),
  > 134|   );
    135| 
    136|   if (!is_null($child_business) && !is_null($child_business[0])) {
Unexpected ')' in ./app/app/Vendor/FacebookAds/facebook/php-ads-sdk/examples/aggregator_onboarding/api.php on line 134
```

```sh
$ vendor/bin/parallel-lint --version
PHP Parallel Lint version 1.0.0
```

**Comment by exussum12** [comment]
You probably want to exclude app/Vendor too ?
`vendor/bin/parallel-lint --exclude vendor --exclude app/app/Vendor .`

Using anything but PHP 7.3 that will be a syntax error

**Comment by codeasashu** [comment]
Ok, the OS I was using this command on, had php 5.5.9 installed, still parallel-lint chose (or preferred) to use php 7.3? Does it not uses OS installed php distribution package?

**Comment by exussum12** [comment]
Depends on the version of parallel lint. Older versions use what ever the command PHP resolves to. Newer versions default to what ever binary called parallel lint. 

You can over ride it in either case by adding the -p flag

**Comment by codeasashu** [comment]
Thanks, I guess I will pay more attention to the documentation from now on. Closing this :)
