### ISSUE TITLE
Optional Git blame

### ISSUE THREAD

**Issue by VasekPurchart** [JakubOnderka/PHP-Parallel-Lint#43]
I stumbled upon the new Git blame functionality introduced in 9930d122439c87275e49fc6550846e55baf46ca1 when updating all my projects to the 0.8 version finally and I noticed (correct me if I am wrong) that there is no straightforward way, to disable this functionality - if it will run is based only on the fact if there is a Git executable.

**Using git blame is not really helpful in a lot of situations (depends on the workflow of the project) blame might not be a good tool for the job at all. And what's more - there are situations, when the file is not even committed to Git yet, so it is outright misleading.**

The only way to disable the functionality is to set the `--git` cmd parameter to an non-existent executable. But I consider this approach really hacky and prone to error (no way to ensure there wont be such an executable on different systems, it's relying on current implementation detail, etc.), 

I would prefer if there was a way to disable this by a cmd parameter (or be disabled by default and only optionally enabled?).

``` bash
# disable blame functionality
./parallel-lint --no-blame . 

# or if it would be disabled by default
./parallel-lint --blame . 
```

Please let me know, that do you think, I can try to prepare a PR, when/if we agree on one of the variants.

**Comment by VasekPurchart** [comment]
@JakubOnderka ping, another try :)

**Comment by JakubOnderka** [comment]
Sorry for later response. PhpParallelLint uses 'porcelain' Git output for machine consumption, so I think is compatible with other clients. And for uncommitted files can be added warning message or don't use blame for these files. 

But personally I am not using this functionality, so if you think it is better disable it by default, you can send me pull request and I merge it.

**Comment by VasekPurchart** [comment]
> But personally I am not using this functionality, so if you think it is better disable it by default, you can send me pull request and I merge it.

I am not using it as well :)

PR is ready: #45 .
