### ISSUE TITLE
Symbolic links should be ignored, or have an option to do turn this on or off

### ISSUE THREAD

**Issue by dbeckham** [JakubOnderka/PHP-Parallel-Lint#46]
Symbolic links are not real PHP files and may, for whatever reason, not resolve to an actual file in a development or CI environment. Symbolic links should be ignored, or be able to be ignored with a command line switch.

Currently, PHP-Parallel-Lint will report `Checked nnnn files in xx seconds, no syntax error found`, but then report `Could not open input file: ...` with an exit status of 1, causing CI tools to fail even though there were no actual lint errors.

I understand that unreadable files, bad permissions, etc. are a good cause to fail QA tests, but symbolic links (along with pipes, directories, etc.) are not regular PHP files and should always be ignored, or least have the option of being ignored.

**Comment by JakubOnderka** [comment]
In last release (version 0.9), it is possible to set '--ignore-fails' argument.
