### ISSUE TITLE
phar file?

### ISSUE THREAD

**Issue by huglester** [JakubOnderka/PHP-Parallel-Lint#48]
Hello

is there a .phar option of this package?

**Comment by temp** [comment]
I just created a phar file, this was relative easy with box.
https://gist.github.com/temp/21805780bf67a106e58c

The only thing that isn't working is the call to bin/skip-linting.php.
Don't know why this has to be a separate process, can't this be done inline?
Maybe the author can help...

**Comment by temp** [comment]
If it can't be done inline, can't this be integrated as a separate switch to parallel-lint.php?
So the phar would call itself for the skip-lint-check...

**Comment by JakubOnderka** [comment]
Hi, now you can create Phar package by Box app. See https://github.com/JakubOnderka/PHP-Parallel-Lint#create-phar-package for futher information. 

Thanks @temp for pull.
