### ISSUE TITLE
What about new release with fix for #40?

### ISSUE THREAD

**Issue by mhujer** [JakubOnderka/PHP-Parallel-Lint#49]
It would be nice to have a release with fix for #40

**Comment by mhujer** [comment]
@JakubOnderka please? :-)

**Comment by mhujer** [comment]
![](http://netdna.walyou.netdna-cdn.com/wp-content/uploads//2012/03/i_are_sad_kitten.jpg)

**Comment by VasekPurchart** [comment]
![cute_cat-wallpaper-](https://cloud.githubusercontent.com/assets/406821/7652424/d393f186-fb0c-11e4-9ca5-3e19fec970eb.jpg)

**Comment by VasekPurchart** [comment]
@JakubOnderka please?

**Comment by mhujer** [comment]
@JakubOnderka please?

**Comment by JakubOnderka** [comment]
:+1:  :dancer:

**Comment by VasekPurchart** [comment]
Thanks! I started to become worried if you are alive :)

**Comment by mhujer** [comment]
:+1:
