### ISSUE TITLE
Light background terminal.

### ISSUE THREAD

**Issue by alasdairdc** [JakubOnderka/PHP-Parallel-Lint#50]
Instead of forcing the color to (almost) white in the case of a white terminal you should be using the reset color "\e[0m". Then this will look better on both light and dark terminals.

**Comment by JakubOnderka** [comment]
Thanks, this is fixed in new realased version of package `jakub-onderka/php-console-highlighter`.

**Comment by alasdairdc** [comment]
Thanks, looks good.
