### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by legoktm** [JakubOnderka/PHP-Parallel-Lint#54]
Hi! Today we had a user on Windows who experienced a bug that had been fixed a while back (#40), but isn't included in a release yet. Could you do a new release that includes that patch?

Thanks!

**Comment by VasekPurchart** [comment]
Duplicate of #49.

**Comment by JakubOnderka** [comment]
Today was released 0.9 version :-)

**Comment by legoktm** [comment]
Thank you!

**Comment by Krinkle** [comment]
Thanks! :star2:
