### ISSUE TITLE
Change of 'property' in errors - Regression ?

### ISSUE THREAD

**Issue by bskart** [JakubOnderka/PHP-Parallel-Lint#56]
Hi,
was there a reason to change the properties-entry in errors to be the same "name" which is already included in the message ?

For me the change was a big regression in terms of failing tests and losing valueable data which allowed us to pinpoint where errors in the json are, which we now cant do anymore.

Before:

``` php
$error = ['property' => 'element[0].anotherelement[0].settings', 'message' => 'The property id is required'];
```

After:

``` php
$error = ['property' => 'id', 'message' => 'The property id is required'];
```

While the property-entry on the first thing helps me quickly find what is really wrong (in a complex schema there might be multiple elements on different levels with the same property-name), the second gives me absolutely nothing, only redundant information which i already have in the message.

Would it be possible to get this "path" back in a way for example as an additional 'path' in the error ?

**Comment by JakubOnderka** [comment]
@bskart Sorry, but I do not understand this issue. It is still actual?
