### ISSUE TITLE
Update instructions on README.md

### ISSUE THREAD

**Issue by msound** [JakubOnderka/PHP-Parallel-Lint#59]
In the README.md section about [Create Phar package](https://github.com/JakubOnderka/PHP-Parallel-Lint/blob/master/README.md#create-phar-package), there are references to http://box-project.org/installer.php

However, the link (and the domain itself) do not seem to be working anymore.

Please provide a work around.

**Comment by msound** [comment]
Found the [project page](https://github.com/box-project/box2) and the correct instruction seems to be:
```
$ curl -LSs http://box-project.github.io/box2/installer.php | php
```

Doing some tests, pull request coming up.

**Comment by JakubOnderka** [comment]
Merged, thank you :)
