### ISSUE TITLE
.inc Files

### ISSUE THREAD

**Issue by TasneemLo** [JakubOnderka/PHP-Parallel-Lint#63]
How do I make parallel-lint parse .php and .inc files ? Currently it seems to be ignoring my .inc files

```
$ find . -name "*.php" | wc -l
25
$ find . -name "*.inc" | wc -l
16
$ ./vendor/bin/parallel-lint .
PHP 5.5.9 | 10 parallel jobs
.........................                                    25/25 (100 %)


Checked 25 files in 0.1 seconds
No syntax error found
```

As seen above, it only checks the 25 .php files I have.

**Comment by grogy** [comment]
Hello,

you can use option `-e <extentensions>`. For example `-e php,php5,ini`.

**Comment by TasneemLo** [comment]
Thanks !
