### ISSUE TITLE
Add option --version

### ISSUE THREAD

**Issue by o5** [JakubOnderka/PHP-Parallel-Lint#71]
I'm implementing this tool into our Continuous Integration and I would like to print version of `parallel-lint` for potentially troubleshooting. 

There is workaround with `sed`, but new option will be nicer.
```
[~]$ parallel-lint | sed -n 1p
PHP Parallel Lint version 0.9.1
```

Version could be also constant instead of [hardcoded string](https://github.com/JakubOnderka/PHP-Parallel-Lint/blob/master/parallel-lint.php#L43). 

Please let me know, if you are open for PR :)
Thanks

**Comment by grogy** [comment]
I agree with this idea. Can you send the PR? :-)
