### ISSUE TITLE
Why do you recommend excluding Symfony's app directory?

### ISSUE THREAD

**Issue by nicwortel** [JakubOnderka/PHP-Parallel-Lint#91]
I was wondering why excluding the "app" directory is [recommended in the README](https://github.com/JakubOnderka/PHP-Parallel-Lint#recommended-setting-for-usage-with-symfony-framework). I'd think that it is useful to check PHP files in "app", such as "AppKernel.php" or the "autoload.php". Is there a specific reason to exclude the directory, and if so, could you add that reason to the README?

**Comment by JakubOnderka** [comment]
The reason was that in Symfony 2 app directory contains generated files in cache directory and I think there is not reason to check syntax for generated files. But maybe it would be better to exclude only `app/cache`. And in Symfony 3, it has no reason, because generated files are in `var` dir.

**Comment by nicwortel** [comment]
Ah, of course. Thanks for the explanation. Still, you'd need to exclude the "var" directory then. Perhaps it is a good idea to add this information to the README? Do you want me to create a PR?
